#!/usr/bin/lua

require "deck"
require "stack"
require "card"

function _init ()
    deck = Deck.new()
    deck.shuffle()

    stack = Stack.new(0)
    for i = 1, 21 do
        stack.draw(deck.deal())
    end
end

function deal ()
    for i = 1, #stack.get_cards(), 3 do
        print("+---+\t+---+\t+---+")
        print("|"    .. stack.get_cards(i).get_id()   .. 
              "|\t|" .. stack.get_cards(i+1).get_id() .. 
              "|\t|" .. stack.get_cards(i+2).get_id() .. "|")
    end
    print("+---+\t+---+\t+---+")
end

function shuffle (location)
    if not (location >= 1 and location <= 3) then
        print("Please enter a number between 1-3")
        return
    end

    local cards = stack.get_cards()

    -- TODO: attempt using conditional assignment to clean this up
    if location == 1 then
        cards[1], cards[4], cards[7], cards[10], cards[13], cards[16], cards[19],
        cards[2], cards[5], cards[8], cards[11], cards[14], cards[17], cards[20],
        cards[3], cards[6], cards[9], cards[12], cards[15], cards[18], cards[21] =
        cards[8], cards[9], cards[10], cards[11], cards[12], cards[13], cards[14],
        cards[1], cards[2], cards[3], cards[4], cards[5], cards[6], cards[7],
        cards[15], cards[16], cards[17], cards[18], cards[19], cards[20], cards[21]
        locator = 0
    elseif location == 2 then
        cards[1], cards[4], cards[7], cards[10], cards[13], cards[16], cards[19],
        cards[2], cards[5], cards[8], cards[11], cards[14], cards[17], cards[20],
        cards[3], cards[6], cards[9], cards[12], cards[15], cards[18], cards[21] =
        cards[1], cards[2], cards[3], cards[4], cards[5], cards[6], cards[7],
        cards[8], cards[9], cards[10], cards[11], cards[12], cards[13], cards[14],
        cards[15], cards[16], cards[17], cards[18], cards[19], cards[20], cards[21]
        locator = locator + 1
    elseif location == 3 then
        cards[1], cards[4], cards[7], cards[10], cards[13], cards[16], cards[19],
        cards[2], cards[5], cards[8], cards[11], cards[14], cards[17], cards[20],
        cards[3], cards[6], cards[9], cards[12], cards[15], cards[18], cards[21] =
        cards[8], cards[9], cards[10], cards[11], cards[12], cards[13], cards[14],
        cards[15], cards[16], cards[17], cards[18], cards[19], cards[20], cards[21],
        cards[1], cards[2], cards[3], cards[4], cards[5], cards[6], cards[7]
        locator = 0
    end

    stack = Stack.new(#cards, cards)
end

function play ()
   _init()
   os.execute("clear")
   
   print("Choose one of the cards below.")
   locator = 0
   
   repeat
       deal()
       io.stdout:write("Which column is your card in? "); shuffle(io.stdin:read("*number"))
       os.execute("clear")
   until locator == 2
   os.execute("clear")
   print("+---+\n|" .. stack.get_cards(11).get_id() .. "| is your card!\n+---+")
end

--[[ Main Function ]] --
repeat
    play()
    io.stdout:write("Play again? [Y/n] "); response = io.stdin:read("*line");
until string.lower(io.stdin:read(1)) == 'n'
